- name: Create File
  hosts: '{{ host }}'
  vars:
    base64Content: "{{ base64Content }}"
  tasks:

    - name: create file with text content
      ansible.builtin.copy:
        content: "{{ content | b64decode }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: base64Content|default(False) == True

    - name: create file with base64 content
      ansible.builtin.copy:
        content: "{{ content }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: base64Content|default(False) == False
