- name: Create File
  hosts: '{{ host }}'
  vars: base64Content: "{{ base64Content | default(omit) }}"
  tasks:
    - name: create file with text content
      ansible.builtin.copy:
        content: "{{ content | b64decode }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: not base64Content

    - name: create file with base64 content
      ansible.builtin.copy:
        content: "{{ content }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: base64Content
