- name: Create File
  hosts: '{{ host }}'

  tasks:
    - name: set facts
      set_fact:
        is_base64_content: "{{ base64Content | default(omit) }}"

    - name: create file with text content
      copy:
        content: "{{ content | b64decode }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: ansible_facts['is_base64_content'] != true

    - name: create file with base64 content
      copy:
        content: "{{ content }}"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
      when: ansible_facts['is_base64_content'] == true

    - name: Display all variables/facts known for a host
      debug:
        var: is_base64_content
        verbosity: 4
