- name: Create File
  hosts: '{{ host }}'
  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      ansible.builtin.copy:
        content: "this is a test"
        dest: "{{ file_path }}"
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        mode: "{{ permissions | default(omit) }}"
