- name: Create File
  hosts: '{{ host }}'
  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      ansible.builtin.copy:
        content: "this is a test"
        dest: "{{ file_path }}"
        owner: "{{ owner | default('') }}"
        group: "{{ group | default('') }}"
        mode: "{{ permissions | default('u=rw,g=r,o=r') }}"
