- name: Delete Directory
  hosts: '{{ host }}'
  vars:
    ansible_ssh_private_key_file: "{{ ssk_key | default(omit) }}"
    ansible_user: "{{ ssh_user | default(omit) }}"
    ansible_password: "{{ ssh_password | default(omit) }}"
    ansible_port: "{{ ssh_port | default(22,boolean=True) }}"
  tasks:
    - name: check if directory exists
      stat:
        path: "{{ path }}"
      register: result

    - fail:
        msg: "{{ path }} not exists."
      when: not result.stat.isdir

    - name: delete directory
      file:
        path: "{{ path }}"
        state: absent
